import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Store, Mail, Lock, Eye, EyeOff, AlertCircle, Loader2 } from 'lucide-react';
import { login } from '../../lib/api';

export default function SellerLoginPage() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPw, setShowPw] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(''); try { await login(email, password, 'seller'); navigate('/seller/dashboard'); } catch (err) { setError(err instanceof Error ? err.message : 'Login failed'); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50 flex flex-col"><header className="px-6 py-4 flex items-center justify-between border-b border-orange-100 bg-white/80"><Link to="/" className="flex items-center gap-2.5"><div className="w-8 h-8 bg-gradient-to-br from-orange-500 to-amber-500 rounded-xl flex items-center justify-center"><Store size={16} className="text-white" /></div><span className="font-extrabold text-gray-900 text-lg">Seller Center</span></Link><Link to="/" className="text-sm text-gray-500">← Back to Shop</Link></header><div className="flex-1 flex items-center justify-center px-4 py-10"><div className="w-full max-w-sm"><div className="flex justify-center mb-6"><div className="w-16 h-16 bg-gradient-to-br from-orange-500 to-amber-500 rounded-2xl flex items-center justify-center shadow-xl shadow-orange-200"><Store size={28} className="text-white" /></div></div><h1 className="text-2xl font-extrabold text-gray-900 text-center mb-1">Welcome back</h1><p className="text-sm text-gray-500 text-center mb-8">Sign in to your Seller Center</p><form onSubmit={handleSubmit} className="bg-white rounded-2xl shadow-xl shadow-gray-100 border border-gray-100 p-6 space-y-4"><div><label className="block text-sm font-semibold text-gray-700 mb-1.5">Email</label><div className="relative"><Mail size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl text-sm"/></div></div><div><label className="block text-sm font-semibold text-gray-700 mb-1.5">Password</label><div className="relative"><Lock size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400"/><input type={showPw?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full pl-10 pr-10 py-3 border border-gray-200 rounded-xl text-sm"/><button type="button" onClick={()=>setShowPw(!showPw)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-gray-400">{showPw?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></div>{error&&<div className="bg-red-50 border border-red-200 rounded-xl p-3 flex items-center gap-2"><AlertCircle size={15} className="text-red-500"/><p className="text-red-600 text-sm">{error}</p></div>}<button disabled={loading} className="w-full bg-orange-500 hover:bg-orange-600 disabled:bg-orange-300 text-white font-bold py-3 rounded-xl text-sm flex items-center justify-center gap-2">{loading?<><Loader2 size={16} className="animate-spin"/> Signing in...</>:'Sign In'}</button></form><p className="text-center text-sm text-gray-500 mt-6">New seller? <Link to="/seller/register" className="text-orange-500 font-semibold">Register your shop</Link></p></div></div></div>;
}
