import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Store, User, Mail, Phone, MapPin, Lock, AlertCircle, Loader2 } from 'lucide-react';
import { register } from '../../lib/api';

export default function SellerRegisterPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ fullName:'', email:'', phone:'', password:'', shopName:'', businessType:'retail', address:'', tradeLicense:'', nidNumber:'' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const setF = (k:string,v:string) => setForm(f=>({...f,[k]:v}));
  const submit = async (e:React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { await register({ ...form, role:'seller' }); navigate('/seller/dashboard'); } catch(err) { setError(err instanceof Error ? err.message : 'Registration failed'); } finally { setLoading(false); } };
  const fields = [ ['fullName','Full Name',User,'text'], ['email','Email',Mail,'email'], ['phone','Phone',Phone,'tel'], ['password','Password',Lock,'password'], ['shopName','Shop Name',Store,'text'], ['address','Shop Address',MapPin,'text'], ['tradeLicense','Trade License No.',Store,'text'], ['nidNumber','NID Number',User,'text'] ] as const;
  return <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50"><header className="px-6 py-4 flex items-center justify-between border-b border-orange-100 bg-white/80"><Link to="/" className="flex items-center gap-2.5"><div className="w-8 h-8 bg-orange-500 rounded-xl flex items-center justify-center"><Store size={16} className="text-white" /></div><span className="font-extrabold text-gray-900 text-lg">Seller Registration</span></Link><Link to="/seller/login" className="text-sm text-orange-500 font-semibold">Login</Link></header><main className="max-w-2xl mx-auto px-4 py-10"><form onSubmit={submit} className="bg-white rounded-2xl border border-gray-100 shadow-xl shadow-gray-100 p-6 space-y-4"><h1 className="text-2xl font-extrabold text-gray-900">Register your shop</h1><p className="text-sm text-gray-500">Your seller account will be pending until an admin approves it.</p><div className="grid sm:grid-cols-2 gap-4">{fields.map(([key,label,Icon,type])=><div key={key}><label className="block text-sm font-semibold text-gray-700 mb-1.5">{label}</label><div className="relative"><Icon size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400"/><input type={type} value={(form as any)[key]} onChange={e=>setF(key,e.target.value)} className="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl text-sm" required={['fullName','email','phone','password','shopName'].includes(key)}/></div></div>)}</div>{error&&<div className="bg-red-50 border border-red-200 rounded-xl p-3 flex gap-2"><AlertCircle size={15} className="text-red-500"/><p className="text-red-600 text-sm">{error}</p></div>}<button disabled={loading} className="w-full bg-orange-500 text-white font-bold py-3 rounded-xl flex justify-center gap-2">{loading?<><Loader2 size={16} className="animate-spin"/> Submitting...</>:'Submit Seller Application'}</button></form></main></div>;
}
