// Generated from src/data/*.ts for MongoDB seeding.

export const heroSlides = [
  {
    id: '1',
    image: 'https://images.pexels.com/photos/5632379/pexels-photo-5632379.jpeg?auto=compress&cs=tinysrgb&w=1400',
    title: 'New Season Arrivals',
    subtitle: 'Discover the latest fashion trends',
  },
  {
    id: '2',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=1400',
    title: 'Top Electronics Deals',
    subtitle: 'Best prices on gadgets & tech',
  },
  {
    id: '3',
    image: 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=1400',
    title: 'Home & Living Sale',
    subtitle: 'Transform your space today',
  },
  {
    id: '4',
    image: 'https://images.pexels.com/photos/1884581/pexels-photo-1884581.jpeg?auto=compress&cs=tinysrgb&w=1400',
    title: 'Sports & Fitness',
    subtitle: 'Gear up for your next adventure',
  },
];

export const products = [
  {
    id: '1',
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    price: 145000,
    originalPrice: 165000,
    image: 'https://images.pexels.com/photos/17952065/pexels-photo-17952065.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/17952065/pexels-photo-17952065.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'phones',
    brand: 'Apple',
    rating: 4.8,
    reviewCount: 2340,
    badge: 'hot',
    discount: 12,
    stock: 15,
    description: 'The iPhone 15 Pro Max features a titanium design, A17 Pro chip, and an advanced camera system with 5x optical zoom. The Super Retina XDR display with ProMotion offers stunning visuals, while the Action Button adds versatile customization options.',
    features: ['A17 Pro chip', '5x Telephoto Camera', 'Titanium Design', 'USB 3 speeds', 'Action Button', 'Up to 29 hours video playback'],
    specifications: { 'Display': '6.7-inch Super Retina XDR', 'Chip': 'A17 Pro', 'Storage': '256GB', 'Rear Camera': '48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto', 'Battery': '4422 mAh', 'OS': 'iOS 17' },
  },
  {
    id: '2',
    name: 'Samsung 55" QLED 4K Smart TV 2024',
    price: 89000,
    originalPrice: 115000,
    image: 'https://images.pexels.com/photos/6976103/pexels-photo-6976103.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/6976103/pexels-photo-6976103.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/5490235/pexels-photo-5490235.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'tv-appliances',
    brand: 'Samsung',
    rating: 4.6,
    reviewCount: 876,
    badge: 'sale',
    discount: 23,
    stock: 8,
    description: 'Experience stunning 4K QLED picture quality with Quantum HDR and a powerful 4K AI processor. Smart TV features include access to all your favourite streaming apps, voice control, and a sleek slim design.',
    features: ['QLED 4K display', 'Quantum HDR', '4K AI Processor', 'Multiple voice assistants', 'Auto Game Mode', '144Hz refresh rate'],
    specifications: { 'Screen Size': '55 inch', 'Resolution': '3840x2160 (4K)', 'Panel': 'QLED', 'Refresh Rate': '144Hz', 'Smart TV': 'Tizen OS', 'HDMI Ports': '4' },
  },
  {
    id: '3',
    name: 'Nike Air Max 270 Running Shoes',
    price: 8500,
    originalPrice: 12000,
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'sports-outdoors',
    brand: 'Nike',
    rating: 4.7,
    reviewCount: 5120,
    badge: 'sale',
    discount: 29,
    stock: 45,
    description: 'The Nike Air Max 270 features Nike\'s biggest heel Air unit yet, with a full-length upper that\'s comfortable and stylish. Perfect for all-day wear with exceptional cushioning.',
    features: ['270 Air heel unit', 'Breathable mesh upper', 'Foam midsole', 'Rubber outsole', 'Padded collar', 'Available in multiple colors'],
    specifications: { 'Type': 'Running / Lifestyle', 'Upper': 'Engineered Mesh', 'Midsole': 'Foam with Air unit', 'Outsole': 'Rubber', 'Closure': 'Lace-up', 'Weight': '320g' },
  },
  {
    id: '4',
    name: 'Dell XPS 15 Laptop Intel Core i7 16GB RAM',
    price: 125000,
    originalPrice: 145000,
    image: 'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'computer-gaming',
    brand: 'Dell',
    rating: 4.9,
    reviewCount: 432,
    badge: 'hot',
    discount: 14,
    stock: 6,
    description: 'The Dell XPS 15 delivers exceptional performance in a thin and light design. With the latest Intel Core i7 processor, 16GB RAM and a stunning 15.6" OLED display, it\'s the perfect machine for professionals and creators.',
    features: ['13th Gen Intel Core i7', 'NVIDIA GeForce RTX 4060', '15.6" OLED 3.5K display', '16GB DDR5 RAM', '512GB NVMe SSD', 'Thunderbolt 4 ports'],
    specifications: { 'Processor': 'Intel Core i7-13700H', 'RAM': '16GB DDR5', 'Storage': '512GB NVMe SSD', 'Display': '15.6" OLED 3456x2160', 'GPU': 'NVIDIA RTX 4060', 'Battery': '86 Whr' },
  },
  {
    id: '5',
    name: "Men's Slim Fit Formal Shirt - Premium Cotton",
    price: 1299,
    originalPrice: 1999,
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2897531/pexels-photo-2897531.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'mens-fashion',
    brand: 'StyleCraft',
    rating: 4.3,
    reviewCount: 1890,
    badge: 'sale',
    discount: 35,
    stock: 120,
    description: 'Crafted from 100% premium cotton, this slim fit formal shirt offers all-day comfort and a polished look. Perfect for office wear or formal occasions, available in multiple colors.',
    features: ['100% premium cotton', 'Slim fit cut', 'Wrinkle resistant', 'Easy care fabric', 'Available in 8 colors', 'Machine washable'],
    specifications: { 'Material': '100% Premium Cotton', 'Fit': 'Slim Fit', 'Collar': 'Spread Collar', 'Sleeve': 'Full Sleeve', 'Care': 'Machine Wash Cold', 'Sizes': 'S, M, L, XL, XXL' },
  },
  {
    id: '6',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    price: 32000,
    originalPrice: 42000,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/8534088/pexels-photo-8534088.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'electronic-accessories',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 3210,
    badge: 'hot',
    discount: 24,
    stock: 22,
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. The WH-1000XM5 features 8 microphones and advanced algorithms for industry-leading noise cancellation, 30-hour battery life, and Multipoint connection.',
    features: ['Industry-leading ANC', '30-hour battery', 'Multipoint connection', '8 microphones', 'Speak-to-Chat', 'Quick Charge (3 min = 3 hrs)'],
    specifications: { 'Driver': '30mm dome type', 'Frequency': '4 Hz - 40,000 Hz', 'Bluetooth': '5.2', 'Battery Life': '30 hours (ANC on)', 'Weight': '250g', 'Noise Cancellation': 'Dual Noise Sensor' },
  },
  {
    id: '7',
    name: "Women's Floral Maxi Dress Summer Collection",
    price: 1850,
    originalPrice: 2500,
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1755428/pexels-photo-1755428.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'womens-fashion',
    brand: 'FloraWear',
    rating: 4.5,
    reviewCount: 2670,
    badge: 'new',
    discount: 26,
    stock: 78,
    description: 'A beautiful floral maxi dress perfect for summer. Made from lightweight, breathable fabric with a flowing silhouette that flatters all body types. Available in multiple floral prints.',
    features: ['Lightweight fabric', 'Floral print', 'Maxi length', 'V-neck design', 'Elastic waistband', 'Pockets included'],
    specifications: { 'Material': '95% Viscose, 5% Elastane', 'Length': 'Maxi (Floor Length)', 'Neckline': 'V-Neck', 'Sleeve': 'Sleeveless', 'Care': 'Hand Wash Only', 'Sizes': 'XS, S, M, L, XL' },
  },
  {
    id: '8',
    name: 'Casio G-Shock GA-2100 Watch Black',
    price: 12500,
    originalPrice: 16000,
    image: 'https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1697214/pexels-photo-1697214.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'watches-bags',
    brand: 'Casio',
    rating: 4.7,
    reviewCount: 987,
    badge: 'sale',
    discount: 22,
    stock: 30,
    description: 'The Casio G-Shock GA-2100 combines the iconic octagonal bezel of the GA-2100 with premium materials. Shock resistant, water resistant to 200M, with world time and LED light.',
    features: ['Shock Resistant', '200M water resistance', 'World Time (48 cities)', 'LED backlight', 'Carbon Core Guard', 'Solar-assist radio timekeeping'],
    specifications: { 'Movement': 'Digital-Analog', 'Water Resistance': '200M', 'Band Material': 'Resin', 'Case Material': 'Resin/Carbon', 'Battery Life': 'Approx. 3 years', 'Weight': '51g' },
  },
  {
    id: '9',
    name: 'Logitech MX Master 3S Wireless Mouse',
    price: 8900,
    originalPrice: 11000,
    image: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'computer-gaming',
    brand: 'Logitech',
    rating: 4.8,
    reviewCount: 1543,
    discount: 19,
    stock: 40,
    description: 'MX Master 3S is an advanced wireless mouse with near-silent clicks, 8K DPI tracking, and electromagnetic MagSpeed scrolling. Works on any surface including glass.',
    features: ['8000 DPI sensor', 'Quiet clicks', 'MagSpeed scroll wheel', 'Works on glass', 'USB-C charging', 'Up to 70 days battery'],
    specifications: { 'DPI': '200-8000', 'Connectivity': 'Bluetooth + USB Receiver', 'Battery': '70 days', 'Buttons': '7 (configurable)', 'Weight': '141g', 'Compatibility': 'Windows, macOS, Linux' },
  },
  {
    id: '10',
    name: "L'Oreal Paris Revitalift Moisturizing Cream SPF50",
    price: 1250,
    originalPrice: 1800,
    image: 'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2253879/pexels-photo-2253879.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'health-beauty',
    brand: "L'Oreal",
    rating: 4.4,
    reviewCount: 4320,
    badge: 'sale',
    discount: 31,
    stock: 200,
    description: 'This daily moisturizer with SPF 50 helps visibly reduce wrinkles while protecting your skin from sun damage. Enriched with Pro-Retinol and SPF 50, it\'s a complete anti-aging solution.',
    features: ['SPF 50 sun protection', 'Pro-Retinol formula', 'Anti-wrinkle action', 'Hydrates 24 hours', 'Suitable for all skin types', 'Non-greasy texture'],
    specifications: { 'Volume': '50ml', 'SPF': '50', 'Skin Type': 'All Types', 'Key Ingredient': 'Pro-Retinol + SPF', 'Usage': 'Daily morning use', 'Texture': 'Light cream' },
  },
  {
    id: '11',
    name: 'Philips Air Fryer HD9270 Dual Basket 7.2L',
    price: 24000,
    originalPrice: 32000,
    image: 'https://images.pexels.com/photos/4668372/pexels-photo-4668372.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/4668372/pexels-photo-4668372.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/6605306/pexels-photo-6605306.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'tv-appliances',
    brand: 'Philips',
    rating: 4.6,
    reviewCount: 765,
    badge: 'sale',
    discount: 25,
    stock: 12,
    description: 'The Philips Air Fryer with dual basket technology lets you cook two different foods simultaneously. 7.2L capacity, rapid hot air technology uses up to 90% less fat than deep frying.',
    features: ['7.2L dual basket capacity', 'Rapid Air Technology', '90% less fat', 'Digital display', 'Dishwasher safe baskets', '13 cooking presets'],
    specifications: { 'Capacity': '7.2L (2x 3.6L)', 'Power': '2000W', 'Temperature': '40-200°C', 'Display': 'Digital Touch', 'Presets': '13 programs', 'Dimensions': '42x35x33cm' },
  },
  {
    id: '12',
    name: 'Mountain Bike 21-Speed Shimano Gear Aluminum Frame',
    price: 35000,
    originalPrice: 45000,
    image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1149601/pexels-photo-1149601.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'sports-outdoors',
    brand: 'Trek',
    rating: 4.5,
    reviewCount: 234,
    badge: 'new',
    discount: 22,
    stock: 7,
    description: 'A versatile mountain bike built for trails and urban riding. Features a lightweight aluminum frame, Shimano 21-speed drivetrain, and hydraulic disc brakes for reliable stopping power in all conditions.',
    features: ['Aluminum alloy frame', 'Shimano 21-speed', 'Hydraulic disc brakes', 'Suspension fork', '27.5" wheels', 'Quick-release axles'],
    specifications: { 'Frame': 'Aluminum Alloy 6061', 'Fork': '100mm travel', 'Drivetrain': 'Shimano 21-speed', 'Brakes': 'Hydraulic Disc', 'Wheel Size': '27.5 inch', 'Weight': '13.5 kg' },
  },
  {
    id: '13',
    name: 'Wooden Coffee Table Modern Minimalist Design',
    price: 18500,
    originalPrice: 25000,
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'home-living',
    brand: 'WoodCraft',
    rating: 4.3,
    reviewCount: 432,
    discount: 26,
    stock: 18,
    description: 'A beautifully crafted minimalist coffee table made from solid oak wood. The clean lines and natural finish add elegance to any living room. Includes a lower shelf for additional storage.',
    features: ['Solid oak construction', 'Minimalist design', 'Lower storage shelf', 'Scratch-resistant finish', 'Easy assembly', 'Supports up to 60kg'],
    specifications: { 'Material': 'Solid Oak Wood', 'Dimensions': '120x60x45 cm', 'Color': 'Natural Oak', 'Weight Capacity': '60 kg', 'Assembly': 'Required', 'Warranty': '2 years' },
  },
  {
    id: '14',
    name: 'Samsung Galaxy S24 Ultra 256GB Titanium Black',
    price: 138000,
    originalPrice: 155000,
    image: 'https://images.pexels.com/photos/12982985/pexels-photo-12982985.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/12982985/pexels-photo-12982985.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'phones',
    brand: 'Samsung',
    rating: 4.8,
    reviewCount: 1876,
    badge: 'hot',
    discount: 11,
    stock: 20,
    description: 'Samsung Galaxy S24 Ultra redefines what a smartphone can do. With an integrated S Pen, the most powerful Snapdragon 8 Gen 3 chip, and a 200MP main camera, it is a true powerhouse.',
    features: ['Snapdragon 8 Gen 3', '200MP main camera', 'Integrated S Pen', '5000mAh battery', '45W fast charging', 'Titanium frame'],
    specifications: { 'Display': '6.8" QHD+ Dynamic AMOLED', 'Chip': 'Snapdragon 8 Gen 3', 'RAM': '12GB', 'Storage': '256GB', 'Main Camera': '200MP', 'Battery': '5000mAh' },
  },
  {
    id: '15',
    name: 'Leather Backpack Men Laptop Bag 15.6"',
    price: 3200,
    originalPrice: 4800,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'watches-bags',
    brand: 'LeatherLux',
    rating: 4.6,
    reviewCount: 1230,
    badge: 'sale',
    discount: 33,
    stock: 55,
    description: 'A premium genuine leather backpack designed for the modern professional. Features a padded 15.6" laptop compartment, multiple organizer pockets, and ergonomic shoulder straps.',
    features: ['Genuine leather', 'Fits 15.6" laptop', 'TSA-friendly design', 'USB charging port', 'Water-resistant lining', 'Ergonomic back padding'],
    specifications: { 'Material': 'Genuine Leather', 'Capacity': '25L', 'Laptop Size': 'Up to 15.6"', 'Dimensions': '44x30x15 cm', 'Weight': '1.2 kg', 'Closure': 'Zipper' },
  },
  {
    id: '16',
    name: 'Baby Stroller Lightweight Foldable Travel System',
    price: 15000,
    originalPrice: 22000,
    image: 'https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=400',
    images: [
      'https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1912868/pexels-photo-1912868.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'mother-baby',
    brand: 'BabySafe',
    rating: 4.7,
    reviewCount: 543,
    badge: 'new',
    discount: 32,
    stock: 14,
    description: 'A lightweight, compact stroller perfect for travel. One-hand fold mechanism, all-terrain wheels, and a reversible seat make this stroller versatile for any adventure.',
    features: ['One-hand fold', 'Reversible seat', 'All-terrain wheels', 'Canopy with UPF 50+', 'Carry bag included', 'Suitable from birth'],
    specifications: { 'Weight': '5.5 kg', 'Max Child Weight': '22 kg', 'Seat': 'Reversible', 'Wheels': 'All-terrain foam', 'Canopy': 'UPF 50+', 'Age': 'From birth to 4 years' },
  },
  // --- New Arrivals ---
  {
    id: '17',
    name: 'Samsung Galaxy Buds3 Pro True Wireless Earbuds',
    price: 18500,
    originalPrice: 22000,
    image: 'https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'electronic-accessories',
    brand: 'Samsung',
    rating: 4.6,
    reviewCount: 312,
    badge: 'new',
    discount: 16,
    stock: 25,
    description: 'Galaxy Buds3 Pro with intelligent ANC and 360 Audio deliver premium sound. The iconic blade design and enhanced comfort make them ideal for all-day wear.',
    features: ['Intelligent ANC', '360 Audio', '24hr total battery', 'IP57 water resistance', 'Blade design', 'Fit & lost detection'],
    specifications: { 'Driver': '10.5mm woofer + 6.1mm tweeter', 'ANC': 'Intelligent', 'Battery (Bud)': '6 hrs', 'Battery (Case)': '18 hrs', 'Bluetooth': '5.4', 'Weight (each)': '5.5g' },
  },
  {
    id: '18',
    name: 'ASUS ROG Strix RGB Gaming Headset',
    price: 9500,
    originalPrice: 13000,
    image: 'https://images.pexels.com/photos/7915437/pexels-photo-7915437.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/7915437/pexels-photo-7915437.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'computer-gaming',
    brand: 'ASUS ROG',
    rating: 4.5,
    reviewCount: 189,
    badge: 'new',
    discount: 27,
    stock: 18,
    description: 'The ROG Strix headset delivers hi-res audio with 50mm ASUS Essence drivers. AI noise-canceling microphone filters out background noise, with plush memory foam earpads for long gaming sessions.',
    features: ['50mm ASUS Essence drivers', 'Hi-Res Audio certified', 'AI noise-canceling mic', 'RGB lighting', 'Memory foam earpads', 'Works on PC/console/mobile'],
    specifications: { 'Driver': '50mm', 'Frequency': '20-20,000Hz', 'Microphone': 'AI Noise Canceling', 'Connection': 'USB-A + 3.5mm', 'Weight': '322g', 'Cable Length': '1.5m' },
  },
  {
    id: '19',
    name: "Puma Men's Jogger Pants - DryCell Technology",
    price: 2299,
    originalPrice: 3200,
    image: 'https://images.pexels.com/photos/4753888/pexels-photo-4753888.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/4753888/pexels-photo-4753888.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'sports-outdoors',
    brand: 'Puma',
    rating: 4.4,
    reviewCount: 567,
    badge: 'new',
    discount: 28,
    stock: 90,
    description: 'Puma DryCell technology wicks away sweat to keep you dry and comfortable during workouts. The tapered fit and elasticated waist with drawcord provide a secure, stylish look.',
    features: ['DryCell moisture-wicking', 'Tapered fit', 'Elasticated waist', 'Side pockets', '88% polyester', 'Machine washable'],
    specifications: { 'Material': '88% Polyester, 12% Elastane', 'Fit': 'Tapered', 'Technology': 'DryCell', 'Closure': 'Drawstring', 'Pockets': '2 side + 1 back', 'Sizes': 'S to 2XL' },
  },
  {
    id: '20',
    name: 'Himalaya Herbals Complete Care Face Wash 200ml',
    price: 350,
    originalPrice: 480,
    image: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'health-beauty',
    brand: 'Himalaya',
    rating: 4.6,
    reviewCount: 8900,
    badge: 'new',
    discount: 27,
    stock: 500,
    description: 'Himalaya\'s herbal face wash with natural extracts cleanses deeply while moisturizing the skin. Free from parabens and SLS, it is gentle enough for everyday use on all skin types.',
    features: ['Natural herbal extracts', 'Deep cleansing', 'Paraben-free', 'SLS-free', 'All skin types', 'Dermatologist tested'],
    specifications: { 'Volume': '200ml', 'Type': 'Gel face wash', 'Skin Type': 'All Types', 'Key Ingredient': 'Neem + Turmeric', 'Usage': 'Twice daily', 'pH': 'Balanced' },
  },
  {
    id: '21',
    name: 'Apple iPad Air M2 11" 128GB Wi-Fi Space Gray',
    price: 75000,
    originalPrice: 85000,
    image: 'https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'computer-gaming',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 654,
    badge: 'new',
    discount: 12,
    stock: 11,
    description: 'iPad Air with M2 chip. Supercharged by the M2 chip, the stunning Liquid Retina display, and advanced cameras, iPad Air is a powerful, versatile canvas for creativity.',
    features: ['M2 chip', '11" Liquid Retina display', '12MP Ultra Wide front camera', 'Wi-Fi 6E', 'USB-C connector', 'All-day battery life'],
    specifications: { 'Chip': 'Apple M2', 'Display': '11-inch Liquid Retina', 'Storage': '128GB', 'Connectivity': 'Wi-Fi 6E', 'Camera': '12MP + 12MP Ultra Wide', 'Battery': 'Up to 10 hours' },
  },
  {
    id: '22',
    name: "Women's Running Sneakers Breathable Lightweight",
    price: 3800,
    originalPrice: 5500,
    image: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'womens-fashion',
    brand: 'Adidas',
    rating: 4.5,
    reviewCount: 1230,
    badge: 'new',
    discount: 31,
    stock: 62,
    description: 'Ultralight running shoes with breathable mesh upper and responsive cushioning. The grippy rubber outsole provides traction on multiple surfaces for versatile everyday wear.',
    features: ['Breathable mesh upper', 'Lightweight cushioning', 'Rubber outsole', 'Padded collar', 'Reflective details', 'Available in 6 colors'],
    specifications: { 'Upper': 'Engineered Mesh', 'Midsole': 'Bounce cushioning', 'Outsole': 'Rubber', 'Weight': '210g', 'Closure': 'Lace-up', 'Sizes': 'UK 3 - 9' },
  },
  // --- Flash Sale ---
  {
    id: '23',
    name: 'Adidas Originals Trefoil Hoodie Unisex',
    price: 3200,
    originalPrice: 5800,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'mens-fashion',
    brand: 'Adidas',
    rating: 4.7,
    reviewCount: 3456,
    badge: 'sale',
    discount: 45,
    stock: 40,
    description: 'Iconic Adidas Originals hoodie with the classic Trefoil logo. Made from soft French terry fabric with a relaxed fit, front kangaroo pocket, and ribbed cuffs and hem.',
    features: ['Classic Trefoil logo', 'French terry fabric', 'Relaxed fit', 'Kangaroo pocket', 'Ribbed cuffs & hem', 'Unisex sizing'],
    specifications: { 'Material': '70% Cotton, 30% Recycled Polyester', 'Fit': 'Relaxed', 'Closure': 'Pullover', 'Pocket': 'Front Kangaroo', 'Care': 'Machine Wash', 'Sizes': 'XS - 3XL' },
  },
  {
    id: '24',
    name: 'JBL Charge 5 Portable Bluetooth Speaker',
    price: 14500,
    originalPrice: 22000,
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'electronic-accessories',
    brand: 'JBL',
    rating: 4.8,
    reviewCount: 2134,
    badge: 'sale',
    discount: 34,
    stock: 16,
    description: 'JBL Charge 5 delivers powerful sound with bold JBL Original Pro Sound. The built-in powerbank charges your devices while its IP67 waterproof and dustproof design lets you take it anywhere.',
    features: ['JBL Original Pro Sound', 'IP67 waterproof + dustproof', '20hr playtime', 'Built-in powerbank', 'JBL PartyBoost', 'USB-C charging'],
    specifications: { 'Output Power': '30W RMS', 'Frequency': '65Hz - 20kHz', 'Bluetooth': '5.1', 'Battery': '7500mAh (20 hrs)', 'Waterproof': 'IP67', 'Dimensions': '22.3x9.6x9.7cm' },
  },
  {
    id: '25',
    name: 'Nikon D3500 DSLR Camera with 18-55mm Lens',
    price: 48000,
    originalPrice: 72000,
    image: 'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'lifestyle-hobbies',
    brand: 'Nikon',
    rating: 4.7,
    reviewCount: 876,
    badge: 'sale',
    discount: 33,
    stock: 9,
    description: 'The Nikon D3500 is the perfect beginner DSLR. Its Guide Mode walks you through each setting, and the incredible battery life of 1550 shots per charge makes it great for long days of shooting.',
    features: ['24.2MP APS-C sensor', '1550 shots per charge', 'Guide Mode', 'Full HD video', 'Bluetooth connectivity', 'Lightweight at 365g'],
    specifications: { 'Sensor': '24.2MP APS-C CMOS', 'ISO': '100-25600', 'Shutter Speed': '1/4000s to 30s', 'Video': '1080p 60fps', 'Battery': 'EN-EL14a (1550 shots)', 'Weight': '365g' },
  },
  {
    id: '26',
    name: 'Dyson V12 Detect Slim Cordless Vacuum Cleaner',
    price: 68000,
    originalPrice: 95000,
    image: 'https://images.pexels.com/photos/4107113/pexels-photo-4107113.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/4107113/pexels-photo-4107113.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'tv-appliances',
    brand: 'Dyson',
    rating: 4.8,
    reviewCount: 432,
    badge: 'sale',
    discount: 28,
    stock: 7,
    description: 'The Dyson V12 Detect Slim uses a laser to reveal hidden dust and automatically boosts suction on carpets. HEPA filtration captures 99.99% of microscopic particles.',
    features: ['Laser dust detection', 'LCD display', 'HEPA filtration', '60-min run time', 'Auto-boost on carpets', 'Lightweight at 2.2kg'],
    specifications: { 'Suction': '150 AW', 'Run Time': 'Up to 60 min', 'Bin Volume': '0.35L', 'Filtration': 'Whole-machine HEPA', 'Weight': '2.2kg', 'Charging': '4.5 hours' },
  },
  {
    id: '27',
    name: 'Mi Smart Band 8 Fitness Tracker 1.62" Display',
    price: 3500,
    originalPrice: 5500,
    image: 'https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/437038/pexels-photo-437038.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'watches-bags',
    brand: 'Xiaomi',
    rating: 4.4,
    reviewCount: 5670,
    badge: 'sale',
    discount: 36,
    stock: 120,
    description: 'Mi Smart Band 8 features a large 1.62" AMOLED display, 16-day battery life, and 150+ sport modes. Blood oxygen and heart rate monitoring keep you on top of your health.',
    features: ['1.62" AMOLED display', '16-day battery', '150+ sport modes', 'Blood oxygen monitoring', '5ATM waterproof', 'Sleep tracking'],
    specifications: { 'Display': '1.62" AMOLED', 'Battery': '190mAh (16 days)', 'Water Resistance': '5ATM', 'Sensors': 'SpO2 + Heart Rate', 'Connectivity': 'Bluetooth 5.3', 'Weight': '27.9g' },
  },
  {
    id: '28',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6Qt',
    price: 12000,
    originalPrice: 19500,
    image: 'https://images.pexels.com/photos/6605300/pexels-photo-6605300.jpeg?auto=compress&cs=tinysrgb&w=400',
    images: ['https://images.pexels.com/photos/6605300/pexels-photo-6605300.jpeg?auto=compress&cs=tinysrgb&w=800'],
    category: 'tv-appliances',
    brand: 'Instant Pot',
    rating: 4.6,
    reviewCount: 12000,
    badge: 'sale',
    discount: 38,
    stock: 35,
    description: 'The Instant Pot Duo replaces 7 kitchen appliances: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer. Cook meals up to 70% faster.',
    features: ['7-in-1 functions', '6 Qt capacity', 'Cook 70% faster', '13 customizable programs', 'Safety tested & certified', 'Easy-to-use panel'],
    specifications: { 'Capacity': '6 Quart', 'Functions': '7-in-1', 'Programs': '13 smart programs', 'Material': 'Stainless steel', 'Watts': '1000W', 'Dimensions': '33x31x32cm' },
  },
];


export const categories = [
  {
    id: '1',
    name: "Men's Fashion",
    image: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'mens-fashion',
  },
  {
    id: '2',
    name: 'Computer & Gaming',
    image: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'computer-gaming',
  },
  {
    id: '3',
    name: 'Home & Living',
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'home-living',
  },
  {
    id: '4',
    name: 'Groceries & Pet Supplies',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'groceries-pet',
  },
  {
    id: '5',
    name: 'Health & Beauty',
    image: 'https://images.pexels.com/photos/2253879/pexels-photo-2253879.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'health-beauty',
  },
  {
    id: '6',
    name: "Women's Fashion",
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'womens-fashion',
  },
  {
    id: '7',
    name: 'TV & Home Appliances',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'tv-appliances',
  },
  {
    id: '8',
    name: 'Lifestyle & Hobbies',
    image: 'https://images.pexels.com/photos/3767411/pexels-photo-3767411.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'lifestyle-hobbies',
  },
  {
    id: '9',
    name: 'Electronic Accessories',
    image: 'https://images.pexels.com/photos/1518044/pexels-photo-1518044.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'electronic-accessories',
  },
  {
    id: '10',
    name: 'Watches & Bags',
    image: 'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'watches-bags',
  },
  {
    id: '11',
    name: 'Sports & Outdoors',
    image: 'https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'sports-outdoors',
  },
  {
    id: '12',
    name: 'Mother & Baby',
    image: 'https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=180',
    slug: 'mother-baby',
  },
  {
    id: '13',
    name: 'Automotives & Motorbikes',
    image: 'https://images.pexels.com/photos/2116475/pexels-photo-2116475.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'automotive',
  },
  {
    id: '14',
    name: 'Phones & Accessories',
    image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=180',
    slug: 'phones',
  },
];

