import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Mail, Lock, User, Phone, ShoppingCart, Package, LogOut, Edit2, AlertCircle, Loader2 } from 'lucide-react';
import { apiFetch, clearSession, getStoredUser, login, register, setSession } from '../lib/api';

type Order = { id:string; order_number:string; status:string; total_amount:number; created_at:string };

function Dashboard({ user }: { user:any }) {
  const navigate = useNavigate();
  const [orders, setOrders] = useState<Order[]>([]);
  const [name, setName] = useState(user.fullName || '');
  const [phone, setPhone] = useState(user.phone || '');
  const [msg, setMsg] = useState('');
  useEffect(() => { apiFetch<Order[]>('/api/orders/my').then(setOrders).catch(()=>setOrders([])); }, []);
  const logout = () => { clearSession(); navigate('/'); };
  const save = async () => { const data = await apiFetch<{user:any}>('/api/auth/me', { method:'PATCH', body: JSON.stringify({ fullName:name, phone }) }); setSession(localStorage.getItem('shoppy_token') || '', data.user); setMsg('Profile saved'); };
  return <div className="min-h-screen bg-gray-50 py-8 px-4"><div className="max-w-2xl mx-auto"><Link to="/" className="flex items-center gap-2 mb-6"><div className="w-8 h-8 bg-orange-500 rounded-lg flex items-center justify-center"><ShoppingCart size={16} className="text-white" /></div><span className="text-lg font-extrabold text-gray-900">Cart<span className="text-orange-500">up</span></span></Link><div className="bg-white rounded-2xl border overflow-hidden mb-4"><div className="bg-gradient-to-r from-orange-500 to-orange-400 px-6 py-5"><p className="text-white font-extrabold text-lg">{name || user.email}</p><p className="text-orange-100 text-sm">{user.email}</p></div><div className="p-5 space-y-5"><div><h2 className="font-bold mb-3 flex gap-2"><Edit2 size={16}/> Edit Profile</h2><div className="grid sm:grid-cols-2 gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="border rounded-xl px-3 py-2 text-sm"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="border rounded-xl px-3 py-2 text-sm"/></div><button onClick={save} className="mt-3 bg-orange-500 text-white px-4 py-2 rounded-xl font-semibold text-sm">Save</button>{msg && <span className="text-green-600 text-sm ml-3">{msg}</span>}</div><div><h2 className="font-bold mb-3 flex gap-2"><Package size={16}/> My Orders</h2>{orders.length===0?<p className="text-gray-400 text-sm">No orders yet.</p>:<div className="space-y-2">{orders.map(o=><div key={o.id} className="flex justify-between bg-gray-50 rounded-xl p-3"><div><b>{o.order_number}</b><p className="text-xs text-gray-400">{new Date(o.created_at).toLocaleDateString()}</p></div><div className="text-right"><p className="font-bold">৳{o.total_amount.toLocaleString()}</p><p className="text-xs capitalize text-gray-500">{o.status}</p></div></div>)}</div>}</div><button onClick={logout} className="flex items-center gap-2 text-red-500 font-semibold"><LogOut size={16}/> Sign Out</button></div></div></div></div>;
}

export default function AccountPage() {
  const [mode, setMode] = useState<'login'|'register'>('login');
  const [form, setForm] = useState({ fullName:'', email:'', phone:'', password:'' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(getStoredUser());
  const setF = (k:string,v:string) => setForm(f=>({...f,[k]:v}));
  const submit = async (e:React.FormEvent) => { e.preventDefault(); setLoading(true); setError(''); try { const u = mode==='login' ? await login(form.email, form.password, 'customer') : await register({ ...form, role:'customer' }); setUser(u); } catch(err) { setError(err instanceof Error ? err.message : 'Failed'); } finally { setLoading(false); } };
  if (user) return <Dashboard user={user} />;
  return <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4"><div className="w-full max-w-md"><Link to="/" className="flex items-center justify-center gap-2 mb-6"><ShoppingCart className="text-orange-500"/><span className="font-extrabold text-xl">Cart<span className="text-orange-500">up</span></span></Link><form onSubmit={submit} className="bg-white rounded-2xl border p-6 space-y-4 shadow-xl shadow-gray-100"><h1 className="text-2xl font-extrabold text-center">{mode==='login'?'Sign in':'Create account'}</h1>{mode==='register' && <><div className="relative"><User size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={form.fullName} onChange={e=>setF('fullName',e.target.value)} placeholder="Full name" className="w-full pl-10 border rounded-xl px-3 py-3 text-sm"/></div><div className="relative"><Phone size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={form.phone} onChange={e=>setF('phone',e.target.value)} placeholder="Phone" className="w-full pl-10 border rounded-xl px-3 py-3 text-sm"/></div></>}<div className="relative"><Mail size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input type="email" value={form.email} onChange={e=>setF('email',e.target.value)} placeholder="Email" className="w-full pl-10 border rounded-xl px-3 py-3 text-sm" required/></div><div className="relative"><Lock size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input type="password" value={form.password} onChange={e=>setF('password',e.target.value)} placeholder="Password" className="w-full pl-10 border rounded-xl px-3 py-3 text-sm" required/></div>{error&&<div className="bg-red-50 border border-red-200 rounded-xl p-3 flex gap-2"><AlertCircle size={15} className="text-red-500"/><p className="text-red-600 text-sm">{error}</p></div>}<button disabled={loading} className="w-full bg-orange-500 text-white font-bold py-3 rounded-xl flex justify-center gap-2">{loading?<><Loader2 size={16} className="animate-spin"/> Please wait...</>:mode==='login'?'Sign In':'Create Account'}</button><button type="button" onClick={()=>setMode(mode==='login'?'register':'login')} className="w-full text-sm text-orange-500 font-semibold">{mode==='login'?'Create a new account':'Already have an account? Sign in'}</button></form></div></div>;
}
